table 'STI - PMO | Matriz de Riscos'
	lineageTag: 29d55f23-8ce4-4d93-8eeb-4cd5e93c7380

	column 'Resumo do Risco'
		dataType: string
		lineageTag: 57155c8e-7d67-462b-9a12-e81e575d2a6a
		summarizeBy: none
		sourceColumn: Resumo do Risco

		annotation SummarizationSetBy = Automatic

	column 'Descrição do Risco'
		dataType: string
		lineageTag: 3ae46050-303d-4010-933f-d4d356e198e5
		summarizeBy: none
		sourceColumn: Descrição do Risco

		annotation SummarizationSetBy = Automatic

	column Projeto
		dataType: string
		lineageTag: 40e6acca-42cc-4c87-834e-58da0ef64f65
		summarizeBy: none
		sourceColumn: Projeto

		annotation SummarizationSetBy = Automatic

	column 'Tipo do Risco'
		dataType: string
		lineageTag: 3ece754d-7a97-41d0-994d-11b2c9aa6cfd
		summarizeBy: none
		sourceColumn: Tipo do Risco

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: be60f387-0195-4a89-a5fe-4202b993bade
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column 'Causa Raiz'
		dataType: string
		lineageTag: 06772726-ef86-48f5-9279-5af68b1bebc5
		summarizeBy: none
		sourceColumn: Causa Raiz

		annotation SummarizationSetBy = Automatic

	column Efeito
		dataType: string
		lineageTag: cca2c890-6879-46b5-be2c-838388e5a72b
		summarizeBy: none
		sourceColumn: Efeito

		annotation SummarizationSetBy = Automatic

	column Probabilidade
		dataType: string
		lineageTag: dc406434-ead3-42d2-9c2a-f3fc35282380
		summarizeBy: none
		sourceColumn: Probabilidade

		annotation SummarizationSetBy = Automatic

	column Impacto
		dataType: string
		lineageTag: 760d756d-559d-45f2-9da5-90b8634e8ecc
		summarizeBy: none
		sourceColumn: Impacto

		annotation SummarizationSetBy = Automatic

	column 'Estratégia de Resposta ao Risco'
		dataType: string
		lineageTag: a1366bac-26a9-4ac0-878b-585f812d20f4
		summarizeBy: none
		sourceColumn: Estratégia de Resposta ao Risco

		annotation SummarizationSetBy = Automatic

	column 'Plano de Contigência'
		dataType: string
		lineageTag: bc63f559-20a4-494e-8a5c-01c90d687391
		summarizeBy: none
		sourceColumn: Plano de Contigência

		annotation SummarizationSetBy = Automatic

	column Prioridade
		dataType: string
		lineageTag: 83e8c419-95f8-4754-887c-6884b44e449f
		summarizeBy: none
		sourceColumn: Prioridade

		annotation SummarizationSetBy = Automatic

	column Responsável
		dataType: string
		lineageTag: e37ea960-0e19-4d23-a379-10131eae361c
		summarizeBy: none
		sourceColumn: Responsável

		annotation SummarizationSetBy = Automatic

	column 'Status do Risco'
		dataType: string
		lineageTag: 8f3d96c3-0f06-4e01-9856-afb74f2751df
		summarizeBy: none
		sourceColumn: Status do Risco

		annotation SummarizationSetBy = Automatic

	column 'Risco Resolvido no Prazo'
		dataType: string
		lineageTag: 5bed2c84-2d5d-4bf8-b9b3-cbe088175d51
		summarizeBy: none
		sourceColumn: Risco Resolvido no Prazo

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: e4f1731f-1c37-4bd9-8f97-998b70e9d73e
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Modificado
		dataType: dateTime
		formatString: General Date
		lineageTag: f19215b4-ddae-4b51-b196-ae47f01469cb
		summarizeBy: none
		sourceColumn: Modificado

		variation Variation
			isDefault
			relationship: 0dfa0feb-1c96-4d3b-8092-77dff3d0d3a3
			defaultHierarchy: LocalDateTable_aeaee89c-ad75-40a3-a59d-c7a1e1b2e136.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Criado
		dataType: dateTime
		formatString: General Date
		lineageTag: 1d87af1f-5a2e-4efd-96fd-ed8da4b9c798
		summarizeBy: none
		sourceColumn: Criado

		variation Variation
			isDefault
			relationship: 2f49a7a5-8b18-4d1c-9dd3-21ae7d0d0fdc
			defaultHierarchy: LocalDateTable_84020fb0-9e85-4a72-94ab-653db4fe33da.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Frente de Trabalho'
		dataType: string
		lineageTag: d9241d28-d5e9-4c34-98a2-d96fae85b0dd
		summarizeBy: none
		sourceColumn: Frente de Trabalho

		annotation SummarizationSetBy = Automatic

	column 'Criado por.title'
		dataType: string
		lineageTag: 205e4659-8d4d-4eee-9a79-e4b05cc3a810
		summarizeBy: none
		sourceColumn: Criado por.title

		annotation SummarizationSetBy = Automatic

	column 'Criado por.email'
		dataType: string
		lineageTag: 51761c62-a627-4e13-ba2d-0e971b092a2a
		summarizeBy: none
		sourceColumn: Criado por.email

		annotation SummarizationSetBy = Automatic

	column 'Modificado por'
		dataType: string
		lineageTag: 238a17f2-5c6d-4c8e-a2fa-26c55cf1eac6
		summarizeBy: none
		sourceColumn: Modificado por

		annotation SummarizationSetBy = Automatic

	column Versão
		dataType: int64
		formatString: 0
		lineageTag: 96db5ad3-f0bb-4a3f-8dd7-18a568d0f050
		summarizeBy: sum
		sourceColumn: Versão

		annotation SummarizationSetBy = Automatic

	column 'Aplicativo Criado por'
		dataType: string
		lineageTag: eca097b5-88f8-4d7b-9e29-a6aa21caf99f
		summarizeBy: none
		sourceColumn: Aplicativo Criado por

		annotation SummarizationSetBy = Automatic

	column 'Data de Identificação'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 170ffa2e-0579-4cbe-8d9e-7de07484a944
		summarizeBy: none
		sourceColumn: Data de Identificação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Prazo para Resolução'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b755569a-6fc0-4eaa-a59b-a72235de4871
		summarizeBy: none
		sourceColumn: Prazo para Resolução

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data da Resolução'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4d5bdca4-d4b7-4532-bc84-614110ad95cb
		summarizeBy: none
		sourceColumn: Data da Resolução

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Classificação Diária'
		dataType: string
		lineageTag: bd13bf43-3850-449b-b088-48692cbfe5c7
		summarizeBy: none
		sourceColumn: Classificação Diária

		annotation SummarizationSetBy = Automatic

	column 'Ponto Diário'
		dataType: string
		lineageTag: 875aa3c7-18ba-462c-9197-cc0b4a544fca
		summarizeBy: none
		sourceColumn: Ponto Diário

		annotation SummarizationSetBy = Automatic

	partition 'STI - PMO | Matriz de Riscos' = m
		mode: import
		queryGroup: Fatos
		source = ```
				let
				    Fonte = SharePoint.Tables("https://rhpcsp-my.sharepoint.com/personal/31479_rhp_com_br/", [Implementation="2.0", ViewMode="All"]),
				    #"df0154b4-958a-47cb-b640-270e05e7856c" = Fonte{[Id="df0154b4-958a-47cb-b640-270e05e7856c"]}[Items],
				    #"Responsável Expandido" = Table.ExpandListColumn(#"df0154b4-958a-47cb-b640-270e05e7856c", "Responsável"),
				    #"Criado por Expandido" = Table.ExpandListColumn(#"Responsável Expandido", "Criado por"),
				    #"Criado por Expandido1" = Table.ExpandRecordColumn(#"Criado por Expandido", "Criado por", {"title", "email"}, {"Criado por.title", "Criado por.email"}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Criado por Expandido1",{"Configuração do rótulo", "Rótulo de retenção", "Rótulo de retenção Aplicado", "Rótulo aplicado por", "O item é um Registro", "Editar", "Anexos", "Contagem de Itens Filhos", "Contagem de Elementos Filho da Pasta", "Aplicativo Modificado por", "Pressione Delete para excluir o ícone.", "ID de Ativo de Conformidade", "Tipo de Conteúdo", "Tipo"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Resumo do Risco", type text}, {"Descrição do Risco", type text}, {"Data de Identificação", type datetime}, {"Projeto", type text}, {"Tipo do Risco", type text}, {"Categoria", type text}, {"Causa Raiz", type text}, {"Efeito", type text}, {"Probabilidade", type text}, {"Impacto", type text}, {"Estratégia de Resposta ao Risco", type text}, {"Plano de Contigência", type text}, {"Prioridade", type text}, {"Responsável", type text}, {"Status do Risco", type text}, {"Prazo para Resolução", type datetime}, {"Data da Resolução", type datetime}, {"Risco Resolvido no Prazo", type text}, {"ID", Int64.Type}, {"Modificado", type datetime}, {"Criado", type datetime}, {"Criado por.title", type text}, {"Criado por.email", type text}, {"Modificado por", type any}, {"Versão", Int64.Type}, {"Aplicativo Criado por", type text}}),
				    #"Mod. Col. Posição - Datas" = Table.ReorderColumns(#"Tipo Alterado",{"Resumo do Risco", "Descrição do Risco", "Projeto", "Tipo do Risco", "Categoria", "Causa Raiz", "Efeito", "Probabilidade", "Impacto", "Estratégia de Resposta ao Risco", "Plano de Contigência", "Prioridade", "Responsável", "Status do Risco", "Risco Resolvido no Prazo", "ID", "Modificado", "Criado", "Criado por.title", "Criado por.email", "Modificado por", "Versão", "Aplicativo Criado por", "Data de Identificação", "Prazo para Resolução", "Data da Resolução"}),
				    #"Mod. Col. Datas" = Table.TransformColumnTypes(#"Mod. Col. Posição - Datas",{{"Data de Identificação", type date}, {"Prazo para Resolução", type date}, {"Data da Resolução", type date}}),
				    #"Adc. Col. Classificação Diária" = Table.AddColumn(#"Mod. Col. Datas", "Classificação Diária", each 
				        if [#"Data da Resolução"] = null and [#"Prazo para Resolução"] = null then "Indefinido"
				        else if [#"Data da Resolução"] <> null and [#"Data da Resolução"] <= [#"Prazo para Resolução"] then "Concluído no Prazo" 
				        else if [#"Data da Resolução"] <> null and [#"Data da Resolução"] > [#"Prazo para Resolução"] then "Concluído Fora do Prazo" 
				        else if [#"Prazo para Resolução"] <> null and Date.From(DateTime.LocalNow()) <= [#"Prazo para Resolução"] then "Em Dia"
				        else if [#"Prazo para Resolução"] <> null and Date.From(DateTime.LocalNow()) > [#"Prazo para Resolução"] then "Atrasado"
				        else "Não Mapeado"),
				    #"Adc. Col. Ponto Diário" = Table.AddColumn(#"Adc. Col. Classificação Diária", "Ponto Diário", each 
				        if [#"Data da Resolução"] = null and [#"Prazo para Resolução"] = null then 0
				        else if [#"Data da Resolução"] <> null and [#"Data da Resolução"] <= [#"Prazo para Resolução"] then 1
				        else if [#"Data da Resolução"] <> null and [#"Data da Resolução"] > [#"Prazo para Resolução"] then 0 
				        else if [#"Prazo para Resolução"] <> null and Date.From(DateTime.LocalNow()) <= [#"Prazo para Resolução"] then 0
				        else if [#"Prazo para Resolução"] <> null and Date.From(DateTime.LocalNow()) > [#"Prazo para Resolução"] then 0
				        else "Não Mapeado"),
				    #"Frente de Trabalho Expandido" = Table.ExpandListColumn(#"Adc. Col. Ponto Diário", "Frente de Trabalho")
				in
				    #"Frente de Trabalho Expandido"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

