WITH BASE_QUALITY AS(
SELECT 
  'Enfermagem' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'MASC', 'F', 'FEM') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a qualidade do atendimento da equipe de enfermagem hoje?'

  UNION ALL

SELECT 
  'Equipe Médica' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'Masc', 'F', 'Fem',TP_SEXO) FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a qualidade do atendimento da equipe médica hoje?'


  UNION ALL

SELECT 
  'Concierges' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'MASC', 'F', 'FEM') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a qualidade do atendimento da nossa equipe de concierges de hospitalidade?'

  UNION ALL

SELECT 
  'Higienização' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'MASC', 'F', 'FEM') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a qualidade do nosso serviço de higienização hoje?'

  UNION ALL

SELECT 
  'Lavanderia' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'MASC', 'F', 'FEM') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a qualidade do nosso serviço de lavanderia/enxoval hoje?'

  UNION ALL

SELECT 
  'Transporte' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'MASC', 'F', 'FEM') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a qualidade do nosso serviço de transporte/remoção hoje?'

  UNION ALL

SELECT 
  'Nutrição' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'MASC', 'F', 'FEM') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a qualidade do nosso serviço de nutrição hoje?'

  UNION ALL

SELECT 
  'Exames' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'MASC', 'F', 'FEM') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a qualidade dos exames realizados hoje?'

  UNION ALL

SELECT 
  'Acomodações' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'MASC', 'F', 'FEM') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a qualidade de nossas acomodações hoje?'

  UNION ALL

SELECT 
  'Hig. Mãos' AS PESQUISA
  ,nps.ID
  , nps.STATUS
  , nps.CD_PACIENTE
  , (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS NM_PACIENTE_ABREV
  , (SELECT 
        CASE 
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 18 THEN '0 - 17 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 17 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 31 THEN '18 - 30 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 30 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) < 61 THEN '31 - 60 Anos'
            WHEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DT_NASCIMENTO) > 61 THEN '60+ Anos'
        END 
    FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS IDADE
  , (SELECT DECODE(TP_SEXO, 'M', 'MASC', 'F', 'FEM') FROM DBAMV.PACIENTE WHERE CD_PACIENTE = NPS.CD_PACIENTE) AS GENERO
  , nps.CD_ATENDIMENTO
  , (SELECT DT_ATENDIMENTO FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ATENDIMENTO
  , (SELECT DT_ALTA FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS DT_ALTA
  , (SELECT 
        CASE
            WHEN DT_ALTA IS NULL THEN 'Internado'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 3 THEN '0 - 2 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 2 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 6 THEN '3 - 5 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 5 AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO < 9 THEN '6 - 8 Dias'
            WHEN DT_ALTA IS NOT NULL AND NVL(DT_ALTA, TRUNC(SYSDATE)) - DT_ATENDIMENTO > 9 THEN '9+ Dias'
        END
     FROM DBAMV.ATENDIME WHERE CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) AS TMP_PERMAN_DIAS
  , CASE
        WHEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO) IS NOT NULL
        THEN (SELECT DS_UNID_INT FROM DBAMV.UNID_INT UI, DBAMV.LEITO LEI, DBAMV.ATENDIME ATE WHERE UI.CD_UNID_INT = LEI.CD_UNID_INT AND LEI.CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
        ELSE (SELECT NM_SETOR FROM DBAMV.SETOR ST, DBAMV.ORI_ATE OA, DBAMV.ATENDIME ATE WHERE ST.CD_SETOR = OA.CD_SETOR AND OA.CD_ORI_ATE = ATE.CD_ORI_ATE AND CD_ATENDIMENTO = NPS.CD_ATENDIMENTO)
    END AS DS_LOCAL
  , nps.DH_RESPOSTA
  , trunc(nps.DH_RESPOSTA) as DT_INTEGRACAO
  , nps.DH_INTEGRACAO
  , resp.VL_RESPOSTA
  --, resp.DS_QUESTIONARIO
  , resp.DS_COMENTARIO
  , resp.DS_MELHORIA
  , (SELECT count(CD_QUALITY_RESPOSTA_NPS) + (10  - count ( cd_quality_resposta_nps)) FROM rhpleitura.des_quality_nps resp2 where resp2.ID = nps.ID ) NR_QUEST_DISPARADO
FROM rhpleitura.des_quality_nps nps 
LEFT JOIN rhpleitura.des_quality_resposta_nps resp ON resp.ID = nps.ID 
WHERE DS_QUESTIONARIO = 'Como você avalia a frequência da higienização das mãos dos profissionais de saúde antes de realizarem os cuidados?'
)
SELECT * FROM BASE_QUALITY