WITH GOOGLE AS (
SELECT
"ID"
, AUTOR
, REGEXP_REPLACE(REVIEW_ID, '[^0-9]') AS REVIEW_ID
, CAST ( SUBSTR ( ESTRELAS,1, INSTR(ESTRELAS,'/')-1) AS NUMBER) AS ESTRELAS
, CASE
    WHEN CAST ( SUBSTR ( ESTRELAS,1, INSTR(ESTRELAS,'/')-1) AS NUMBER) = 5 THEN INITCAP('ÓTIMO')
    WHEN CAST ( SUBSTR ( ESTRELAS,1, INSTR(ESTRELAS,'/')-1) AS NUMBER) = 4 THEN INITCAP('BOM')
    WHEN CAST ( SUBSTR ( ESTRELAS,1, INSTR(ESTRELAS,'/')-1) AS NUMBER) = 3 THEN INITCAP('REGULAR')
    WHEN CAST ( SUBSTR ( ESTRELAS,1, INSTR(ESTRELAS,'/')-1) AS NUMBER) = 2 THEN INITCAP('RUIM')
    WHEN CAST ( SUBSTR ( ESTRELAS,1, INSTR(ESTRELAS,'/')-1) AS NUMBER) = 1 THEN INITCAP('PÉSSIMO')
  END CAT_ESTRELAS
, DATA_REVIEW
, CASE
    WHEN DATA_REVIEW LIKE '%dia%' THEN 
                DT_COLETA - (
                    CASE 
                        WHEN REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+') IS NOT NULL 
                            THEN TO_NUMBER(REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+'))
                        ELSE 1
                    END
                )
    WHEN DATA_REVIEW LIKE '%semana%' 
    THEN DT_COLETA - (
          CASE 
            WHEN REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+') IS NOT NULL 
            THEN TO_NUMBER(REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+'))
            ELSE 1
          END * 7
            )
    WHEN DATA_REVIEW LIKE '%mes%' 
    THEN ADD_MONTHS(DT_COLETA,-(
                    CASE 
                      WHEN REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+') IS NOT NULL 
                      THEN TO_NUMBER(REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+'))
                      ELSE 1
                    END
                )
            )
    WHEN DATA_REVIEW LIKE '%mês%' 
    THEN ADD_MONTHS(DT_COLETA,-(
                    CASE 
                      WHEN REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+') IS NOT NULL 
                      THEN TO_NUMBER(REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+'))
                      ELSE 1
                    END
                )
            )
    WHEN DATA_REVIEW LIKE '%ano%' 
    THEN ADD_MONTHS( DT_COLETA, - (
                    CASE 
                      WHEN REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+') IS NOT NULL 
                      THEN TO_NUMBER(REGEXP_SUBSTR(DATA_REVIEW,'[0-9]+'))
                      ELSE 1
                    END * 12
                )
            )
    END AS DATA_REGISTRADA
, TEXTO_PACIENTE
, DATA_RESPOSTA_RHP
, CASE
    WHEN DATA_RESPOSTA_RHP LIKE '%dia%' THEN 
            DT_COLETA - (
                CASE 
                    WHEN REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+') IS NOT NULL 
                        THEN TO_NUMBER(REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+'))
                    ELSE 1
                END
            )
    WHEN DATA_RESPOSTA_RHP LIKE '%semana%' 
    THEN DT_COLETA - (
          CASE 
            WHEN REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+') IS NOT NULL 
            THEN TO_NUMBER(REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+'))
            ELSE 1
          END * 7
            )
    WHEN DATA_RESPOSTA_RHP LIKE '%mes%' 
    THEN ADD_MONTHS(DT_COLETA,-(
                    CASE 
                      WHEN REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+') IS NOT NULL 
                      THEN TO_NUMBER(REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+'))
                      ELSE 1
                    END
                )
            )
    WHEN DATA_RESPOSTA_RHP LIKE '%mês%' 
    THEN ADD_MONTHS(DT_COLETA,-(
                    CASE 
                      WHEN REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+') IS NOT NULL 
                      THEN TO_NUMBER(REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+'))
                      ELSE 1
                    END
                )
            )
    WHEN DATA_RESPOSTA_RHP LIKE '%ano%' 
    THEN ADD_MONTHS( SYSDATE, - (
                    CASE 
                      WHEN REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+') IS NOT NULL 
                      THEN TO_NUMBER(REGEXP_SUBSTR(DATA_RESPOSTA_RHP,'[0-9]+'))
                      ELSE 1
                    END * 12
                )
            )
    END AS DATA_RESP_RHP
, RESPOSTA_RHP
, CASE WHEN RESPOSTA_RHP IS NOT NULL THEN 'S' ELSE 'N' END SN_RESPOSTA_RHP
, DT_COLETA

,CASE
  WHEN LENGTH(TEXTO_PACIENTE) > 2 THEN 'S'
END AS SN_COMENTARIO_VALIDO
FROM RHPLEITURA.GOOGLE_REVIEWS
)
SELECT 
ROW_NUMBER() OVER(PARTITION BY AUTOR ORDER BY DATA_REGISTRADA DESC) RANK_DUPLICATA
, GOOGLE.* 

, EXTRACT(YEAR FROM DATA_REGISTRADA) AS DT_REG_AN0
, EXTRACT(MONTH FROM DATA_REGISTRADA) AS DT_REG_MES
, TO_CHAR(TO_DATE(EXTRACT(MONTH FROM DATA_REGISTRADA), 'MM'), 'MON', 'NLS_DATE_LANGUAGE=PORTUGUESE') AS DT_REG_MES_ABREV
, EXTRACT(YEAR FROM DATA_REGISTRADA)||'/'||TO_CHAR(TO_DATE(EXTRACT(MONTH FROM DATA_REGISTRADA), 'MM'), 'MON', 'NLS_DATE_LANGUAGE=PORTUGUESE') AS DT_REG_COMP

, EXTRACT(YEAR FROM DATA_RESP_RHP) AS DT_RESP_AN0
, EXTRACT(MONTH FROM DATA_RESP_RHP) AS DT_RESP_MES
, TO_CHAR(TO_DATE(EXTRACT(MONTH FROM DATA_RESP_RHP), 'MM'), 'MON', 'NLS_DATE_LANGUAGE=PORTUGUESE') AS DT_RESP_MES_ABREV
, EXTRACT(YEAR FROM DATA_RESP_RHP)||'/'||TO_CHAR(TO_DATE(EXTRACT(MONTH FROM DATA_RESP_RHP), 'MM'), 'MON', 'NLS_DATE_LANGUAGE=PORTUGUESE') AS DT_RESP_COMP

, CASE 
    WHEN ROUND(( (NVL(DATA_RESP_RHP, SYSDATE)- DATA_REGISTRADA) * 24 * 60) , 0) < (1440*7)
    THEN ROUND(( (NVL(DATA_RESP_RHP, SYSDATE)- DATA_REGISTRADA) * 24 * 60) , 0)
    ELSE ROUND(( (NVL(DATA_RESP_RHP, (DATA_REGISTRADA + INTERVAL '7' DAY))- DATA_REGISTRADA) * 24 * 60) , 0)
  END AS TMP_RESPOSTA
, (1440*2) AS TMP_SLA
FROM GOOGLE
